### ISSUE TITLE
Ruby comments in code blocks are included as ToC entries

### ISSUE THREAD

**Issue by eebs** [bkuhlmann/tocer#2]
## Expected Behavior
When a document has ruby code blocks that contain comments, the comments should not be included in the table of contents.

The following document is an example of what should happen:

````
<!-- Tocer[start]: Auto-generated, don't remove. -->

# Table of Contents

- [Introduction](#introduction)
  - [Code Blocks](#code-blocks)

<!-- Tocer[finish]: Auto-generated, don't remove. -->


# Introduction

Text here

## Code Blocks

```ruby
# This is a comment describing the code
class MyRubyClass
end
```
````

## Actual Behavior

The actual behavior is to include ruby comments as table of contents entries:

````
<!-- Tocer[start]: Auto-generated, don't remove. -->

# Table of Contents

- [Introduction](#introduction)
  - [Code Blocks](#code-blocks)
- [This is a comment describing the code](#this-is-a-comment-describing-the-code)

<!-- Tocer[finish]: Auto-generated, don't remove. -->


# Introduction

Text here

## Code Blocks

```ruby
# This is a comment describing the code
class MyRubyClass
end
```
````

## Steps to Recreate

1. Run `tocer -g README.md` inside the [eebs/tocer_test](https://github.com/eebs/tocer_test) repo.

## Environment
Tocer 3.1.1
Ruby 2.3.1
OSX 10.11.6

**Comment by bkuhlmann** [comment]
Thanks for catching this. I've fixed the issue on the `release` branch and plan to have a new release out by the weekend. If you need this fix sooner, here is how you can get it now. Do the following steps:

```
git clone https://github.com/bkuhlmann/tocer.git
cd tocer
git checkout release
bundle install
bundle exec rake install
```

**Comment by eebs** [comment]
Awesome thanks, I checked out the release branch and can confirm it no longer includes ruby comments. Thanks for the quick fix!

**Comment by bkuhlmann** [comment]
Yeah, no problem. I'm closing this issue now that [Version 3.2.0](https://github.com/bkuhlmann/tocer/releases/tag/v3.2.0) has been released with the appropriate fix.
