### ISSUE TITLE
Adds blank lines to files with no markdown headers

### ISSUE THREAD

**Issue by paul** [bkuhlmann/tocer#6]
## Overview

We have a markdown file in our wiki with no `#header` elements:

```markdown
Design assets like logos and icons can be found on Google Drive.
https://drive.google.com/drive/u/3/folders/xyz
```

An automated script runs tocer to generate a TOC for all markdown files in the directory. This file currently has 12,150 blank lines preceeding the two lines of content, and `12162` commits in the git log for it.

## Steps to Recreate

```
$ tail Design-Resources.md








Design assets like logos and icons can be found on Google Drive.
https://drive.google.com/drive/u/3/folders/xyz

$ tocer --version
Tocer 12.0.1

$ tocer -b -i Design-Resources.md
  Design-Resources.md

$ git diff | xclip
diff --git a/Design-Resources.md b/Design-Resources.md
index 4491ed77..d8bfcb56 100644
--- a/Design-Resources.md
+++ b/Design-Resources.md
@@ -12148,6 +12148,7 @@
 
 
 
+
 
 
 Design assets like logos and icons can be found on Google Drive.

```

## Desired Behavior

Tocer should not modify files if it did not make any changes. 

## Environment

```
$ uname -a
Linux ava.home 5.11.20-200.fc33.x86_64 #1 SMP Wed May 12 12:48:34 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

$ ruby --version
ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-linux]

$ gem --version
3.2.15

$ tocer --version
Tocer 12.0.1
```

**Comment by bkuhlmann** [comment]
**Paul**: Thanks for finding this and sorry about the trouble. If you upgrade to [12.0.2](https://www.alchemists.io/projects/tocer/changes.html), this issue will go away. I'm assuming this was happening during Wiki update/generation? Hoping maybe you can collapse all those commits down to a single commit and force push maybe? I'm going to close this but let me know if if you hit further issues.
